### ISSUE TITLE
Prevent players from using bonemeal in towns/claims they can't build in, or log instances of it occuring

### ISSUE THREAD

**Issue by drewdorris** [Ruinscraft/mcatlas-towny-helpers#1]
Towny does not prevent this for some reason

**Comment by ds58** [comment]
Likely fixed in newer version of towny

**Comment by ds58** [comment]
This is already a feature of towny. See https://github.com/TownyAdvanced/Towny/issues/3298

our config is probably out of date or doesn't include the bone meal item
